/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/oaLw4hH2mox
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { AssignmentModal } from "@/components/component/assignment-modal"

export default function StudentPortal() {
    const [activeTab, setActiveTab] = useState("progress")
    const [assignmentTab, setAssignmentTab] = useState("current")
    const [open, setOpen] = useState(false)
    const handleFileChange = (event) => {
        const file = event.target.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = (e) => {
                const content = e.target.result;
                setFileContent(content);
                localStorage.setItem('fileContent', content);
                if (file.type.startsWith('text/'))
                    console.log(reader.readAsText(file));
                else if (file?.type.startsWith('image/')) { console.log(reader.readAsDataURL(file)) }
            };



        }
    };
    return (
        (<div className="flex flex-col w-full min-h-screen bg-background">
            <header
                className="sticky top-0 z-10 flex items-center  h-16 px-4 border-b bg-[#FBFBFB] shadow sm:px-6">
                <nav className="flex gap-6 text-lg font-medium md:gap-8">
                <Button
        variant='ghost'
            >
           <img src="https://student.saylaniwelfare.com/assets/logo-OpazD70S.png" className="w-20 " alt="" />
          </Button>
                   <Button
                        variant={activeTab === "progress" ? "secondary" : "ghost"}
                        onClick={() => setActiveTab("progress")}
                        className="px-4 py-2 rounded-md">
                        Progress
                    </Button>
                    <Button
                        variant={activeTab === "attendance" ? "secondary" : "ghost"}
                        onClick={() => setActiveTab("attendance")}
                        className="px-4 py-2 rounded-md">
                        Attendance
                    </Button>
                    <Button
                        variant={activeTab === "quiz" ? "secondary" : "ghost"}
                        onClick={() => setActiveTab("quiz")}
                        className="px-4 py-2 rounded-md">
                        Quiz
                    </Button>
                    <Button
                        variant={activeTab === "assignments" ? "secondary" : "ghost"}
                        onClick={() => setActiveTab("assignments")}
                        className="px-4 py-2 rounded-md">
                        Assignments
                    </Button>
                    <Button
                        variant={activeTab === "payment" ? "secondary" : "ghost"}
                        onClick={() => setActiveTab("payment")}
                        className="px-4 py-2 rounded-md">
                        Payment
                    </Button>
                </nav>
            </header>
            <div className="flex flex-1">
                <main className="flex-1 px-4 py-8 sm:px-6">
                    {activeTab === "progress" && (
                        <Card>
                            <CardHeader>
                                <CardTitle>Progress</CardTitle>
                                <CardDescription>View your overall progress and performance.</CardDescription>
                            </CardHeader>
                            <CardContent>
                                <Table>
                                    <TableHeader>
                                        <TableRow>
                                            <TableHead>Course</TableHead>
                                            <TableHead>Progress</TableHead>
                                            <TableHead>Grade</TableHead>
                                        </TableRow>
                                    </TableHeader>
                                    <TableBody>
                                        <TableRow>
                                            <TableCell>Introduction to Programming</TableCell>
                                            <TableCell>
                                                <div className="w-full h-2 bg-muted rounded-full">
                                                    <div className="h-full bg-primary rounded-full w-[75%]" />
                                                </div>
                                            </TableCell>
                                            <TableCell>A-</TableCell>
                                        </TableRow>
                                        <TableRow>
                                            <TableCell>Data Structures and Algorithms</TableCell>
                                            <TableCell>
                                                <div className="w-full h-2 bg-muted rounded-full">
                                                    <div className="h-full bg-primary rounded-full w-[90%]" />
                                                </div>
                                            </TableCell>
                                            <TableCell>B+</TableCell>
                                        </TableRow>
                                        <TableRow>
                                            <TableCell>Web Development Fundamentals</TableCell>
                                            <TableCell>
                                                <div className="w-full h-2 bg-muted rounded-full">
                                                    <div className="h-full bg-primary rounded-full w-[85%]" />
                                                </div>
                                            </TableCell>
                                            <TableCell>A</TableCell>
                                        </TableRow>
                                        <TableRow>
                                            <TableCell>Mobile App Development</TableCell>
                                            <TableCell>
                                                <div className="w-full h-2 bg-muted rounded-full">
                                                    <div className="h-full bg-primary rounded-full w-[80%]" />
                                                </div>
                                            </TableCell>
                                            <TableCell>B</TableCell>
                                        </TableRow>
                                    </TableBody>
                                </Table>
                            </CardContent>
                        </Card>
                    )}
                    {activeTab === "attendance" && (
                        <Card>
                            <CardHeader>
                                <CardTitle>Attendance</CardTitle>
                                <CardDescription>View your attendance record for the current semester.</CardDescription>
                            </CardHeader>
                            <CardContent>
                                <Table>
                                    <TableHeader>
                                        <TableRow>
                                            <TableHead>Course</TableHead>
                                            <TableHead>Attended</TableHead>
                                            <TableHead>Missed</TableHead>
                                        </TableRow>
                                    </TableHeader>
                                    <TableBody>
                                        <TableRow>
                                            <TableCell>Introduction to Programming</TableCell>
                                            <TableCell>25</TableCell>
                                            <TableCell>3</TableCell>
                                        </TableRow>
                                        <TableRow>
                                            <TableCell>Data Structures and Algorithms</TableCell>
                                            <TableCell>28</TableCell>
                                            <TableCell>1</TableCell>
                                        </TableRow>
                                        <TableRow>
                                            <TableCell>Web Development Fundamentals</TableCell>
                                            <TableCell>27</TableCell>
                                            <TableCell>2</TableCell>
                                        </TableRow>
                                        <TableRow>
                                            <TableCell>Mobile App Development</TableCell>
                                            <TableCell>26</TableCell>
                                            <TableCell>3</TableCell>
                                        </TableRow>
                                    </TableBody>
                                </Table>
                            </CardContent>
                        </Card>
                    )}
                    {activeTab === "quiz" && (
                        <Card>
                            <CardHeader>
                                <CardTitle>Quiz</CardTitle>
                                <CardDescription>Review your quiz performance and scores.</CardDescription>
                            </CardHeader>
                            <CardContent>
                                <Table>
                                    <TableHeader>
                                        <TableRow>
                                            <TableHead>Course</TableHead>
                                            <TableHead>Quiz</TableHead>
                                            <TableHead>Score</TableHead>
                                        </TableRow>
                                    </TableHeader>
                                    <TableBody>
                                        <TableRow>
                                            <TableCell>Introduction to Programming</TableCell>
                                            <TableCell>Quiz 1</TableCell>
                                            <TableCell>90%</TableCell>
                                        </TableRow>
                                        <TableRow>
                                            <TableCell>Data Structures and Algorithms</TableCell>
                                            <TableCell>Quiz 2</TableCell>
                                            <TableCell>85%</TableCell>
                                        </TableRow>
                                        <TableRow>
                                            <TableCell>Web Development Fundamentals</TableCell>
                                            <TableCell>Quiz 1</TableCell>
                                            <TableCell>92%</TableCell>
                                        </TableRow>
                                        <TableRow>
                                            <TableCell>Mobile App Development</TableCell>
                                            <TableCell>Quiz 3</TableCell>
                                            <TableCell>88%</TableCell>
                                        </TableRow>
                                    </TableBody>
                                </Table>
                            </CardContent>
                        </Card>
                    )}
                    {activeTab === "assignments" && (
                        <div>
                            <div className="flex gap-4 mb-4">
                                <Button
                                    variant={assignmentTab === "current" ? "secondary" : "ghost"}
                                    onClick={() => setAssignmentTab("current")}
                                    className="px-4 py-2 rounded-md">
                                    Current
                                </Button>
                                <Button
                                    variant={assignmentTab === "submitted" ? "secondary" : "ghost"}
                                    onClick={() => setAssignmentTab("submitted")}
                                    className="px-4 py-2 rounded-md">
                                    Submitted
                                </Button>
                                <Button
                                    variant={assignmentTab === "failed" ? "secondary" : "ghost"}
                                    onClick={() => setAssignmentTab("failed")}
                                    className="px-4 py-2 rounded-md">
                                    Failed
                                </Button>
                            </div>
                            {assignmentTab === "current" && (
                                <div className="grid grid-cols-[1fr_200px] gap-4">
                                    <Card>
                                        <CardHeader>
                                            <CardTitle>Current Assignments</CardTitle>
                                            <CardDescription>View your current assignment submissions and grades.</CardDescription>
                                        </CardHeader>
                                        <CardContent>
                                            <Table>
                                                <TableHeader>
                                                    <TableRow>
                                                        <TableHead>Assignment</TableHead>
                                                        <TableHead>Deadline</TableHead>
                                                        <TableHead>Submit</TableHead>
                                                    </TableRow>
                                                </TableHeader>
                                                <TableBody>
                                                    <TableRow>
                                                        <TableCell>Introduction to Programming Assignment 1</TableCell>
                                                        <TableCell>2023-06-30</TableCell>
                                                        <TableCell>
                                                            <AssignmentModal variant='outline' text='Upload File' />
                                                        </TableCell>
                                                    </TableRow>
                                                    {open && {

                                                    }}
                                                    <TableRow>
                                                        <TableCell>Data Structures and Algorithms Assignment 2</TableCell>
                                                        <TableCell>2023-07-15</TableCell>
                                                        <TableCell>
                                                            <AssignmentModal variant='outline' text='Upload File' />
                                                        </TableCell>
                                                    </TableRow>
                                                    <TableRow>
                                                        <TableCell>Web Development Fundamentals Assignment 3</TableCell>
                                                        <TableCell>2023-08-01</TableCell>
                                                        <TableCell>
                                                            <AssignmentModal isDisabled={false} variant='outline' text='Upload File' />
                                                        </TableCell>
                                                    </TableRow>
                                                    <TableRow>
                                                        <TableCell>Mobile App Development Assignment 1</TableCell>
                                                        <TableCell>2023-07-31</TableCell>
                                                        <TableCell>
                                                            <AssignmentModal isDisabled={false} variant='outline' text='Upload File' />
                                                        </TableCell>
                                                    </TableRow>
                                                </TableBody>
                                            </Table>
                                        </CardContent>
                                    </Card>
                                    <div className="bg-muted rounded-lg p-4">
                                        <h3 className="text-lg font-bold mb-4">Leaderboard</h3>
                                        <div className="space-y-2">
                                            <div className="flex items-center justify-between">
                                                <div>1. John Doe</div>
                                                <div className="font-bold">95%</div>
                                            </div>
                                            <div className="flex items-center justify-between">
                                                <div>2. Jane Smith</div>
                                                <div className="font-bold">92%</div>
                                            </div>
                                            <div className="flex items-center justify-between">
                                                <div>3. Michael Johnson</div>
                                                <div className="font-bold">88%</div>
                                            </div>
                                            <div className="flex items-center justify-between">
                                                <div>4. Emily Davis</div>
                                                <div className="font-bold">85%</div>
                                            </div>
                                            <div className="flex items-center justify-between">
                                                <div>5. David Lee</div>
                                                <div className="font-bold">82%</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            )}
                            {assignmentTab === "submitted" && (
                                <div className="grid grid-cols-[1fr_200px] gap-4">
                                    <Card>
                                        <CardHeader>
                                            <CardTitle>Submitted Assignments</CardTitle>
                                            <CardDescription>View your submitted assignment grades.</CardDescription>
                                        </CardHeader>
                                        <CardContent>
                                            <Table>
                                                <TableHeader>
                                                    <TableRow>
                                                        <TableHead>Course</TableHead>
                                                        <TableHead>Assignment</TableHead>
                                                        <TableHead>Grade</TableHead>
                                                        <TableHead>View</TableHead>
                                                    </TableRow>
                                                </TableHeader>
                                                <TableBody>
                                                    <TableRow>
                                                        <TableCell>Introduction to Programming</TableCell>
                                                        <TableCell>Assignment 1</TableCell>
                                                        <TableCell>95/100</TableCell>
                                                        <TableCell>
                                                            <AssignmentModal variant={''} isDisabled='' text={'view'} />
                                                        </TableCell>
                                                    </TableRow>
                                                    <TableRow>
                                                        <TableCell>Data Structures and Algorithms</TableCell>
                                                        <TableCell>Assignment 2</TableCell>
                                                        <TableCell>88/100</TableCell>
                                                        <TableCell>
                                                            <AssignmentModal variant={''} isDisabled='' text={'view'} />
                                                        </TableCell>
                                                    </TableRow>
                                                    <TableRow>
                                                        <TableCell>Web Development Fundamentals</TableCell>
                                                        <TableCell>Assignment 3</TableCell>
                                                        <TableCell>92/100</TableCell>
                                                        <TableCell>
                                                            <AssignmentModal variant={''} isDisabled='' text={'view'} />
                                                        </TableCell>
                                                    </TableRow>
                                                    <TableRow>
                                                        <TableCell>Mobile App Development</TableCell>
                                                        <TableCell>Assignment 1</TableCell>
                                                        <TableCell>90/100</TableCell>
                                                        <TableCell>
                                                            <AssignmentModal variant={''} isDisabled={true} text={'view'} />
                                                        </TableCell>
                                                    </TableRow>
                                                </TableBody>
                                            </Table>
                                        </CardContent>
                                    </Card>
                                    <div className="bg-muted rounded-lg p-4">
                                        <h3 className="text-lg font-bold mb-4">Leaderboard</h3>
                                        <div className="space-y-2">
                                            <div className="flex items-center justify-between">
                                                <div>1. John Doe</div>
                                                <div className="font-bold">95%</div>
                                            </div>
                                            <div className="flex items-center justify-between">
                                                <div>2. Jane Smith</div>
                                                <div className="font-bold">92%</div>
                                            </div>
                                            <div className="flex items-center justify-between">
                                                <div>3. Michael Johnson</div>
                                                <div className="font-bold">88%</div>
                                            </div>
                                            <div className="flex items-center justify-between">
                                                <div>4. Emily Davis</div>
                                                <div className="font-bold">85%</div>
                                            </div>
                                            <div className="flex items-center justify-between">
                                                <div>5. David Lee</div>
                                                <div className="font-bold">82%</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            )}
                            {assignmentTab === "failed" && (
                                <div className="grid grid-cols-[1fr_200px] gap-4">
                                    <Card>
                                        <CardHeader>
                                            <CardTitle>Failed Assignments</CardTitle>
                                            <CardDescription>View your failed assignment grades.</CardDescription>
                                        </CardHeader>
                                        <CardContent>
                                            <Table>
                                                <TableHeader>
                                                    <TableRow>
                                                        <TableHead>Assignment</TableHead>
                                                        <TableHead>Deadline</TableHead>
                                                        <TableHead>Grade</TableHead>
                                                        <TableHead>View</TableHead>
                                                    </TableRow>
                                                </TableHeader>
                                                <TableBody>
                                                    <TableRow>
                                                        <TableCell>Introduction to Programming Assignment 2</TableCell>
                                                        <TableCell>2023-06-30</TableCell>
                                                        <TableCell>-</TableCell>
                                                        <TableCell>
                                                            <AssignmentModal isDisabled={true} variant={'destructive'} text={'view'} />
                                                        </TableCell>
                                                    </TableRow>
                                                </TableBody>
                                            </Table>
                                        </CardContent>
                                    </Card>
                                    <div className="bg-muted rounded-lg p-4">
                                        <h3 className="text-lg font-bold mb-4">Leaderboard</h3>
                                        <div className="space-y-2">
                                            <div className="flex items-center justify-between">
                                                <div>1. John Doe</div>
                                                <div className="font-bold">95%</div>
                                            </div>
                                            <div className="flex items-center justify-between">
                                                <div>2. Jane Smith</div>
                                                <div className="font-bold">92%</div>
                                            </div>
                                            <div className="flex items-center justify-between">
                                                <div>3. Michael Johnson</div>
                                                <div className="font-bold">88%</div>
                                            </div>
                                            <div className="flex items-center justify-between">
                                                <div>4. Emily Davis</div>
                                                <div className="font-bold">85%</div>
                                            </div>
                                            <div className="flex items-center justify-between">
                                                <div>5. David Lee</div>
                                                <div className="font-bold">82%</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            )}
                        </div>
                    )}
                </main>
            </div>
        </div>)
    );
}
